theme: minima
title: Open Source Future
author: Pankaj  Biradar 
email: pankaj28988@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Open Source is the art of contributing to Open Source Software
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
